author: mrmag518
main: com.mrmag518.ChestShopUtil.CSU
version: '1.0'
name: ChestShopUtil
description: "Adds new utilities and features to ChestShop."
softdepend: [ChestShop]
commands:
  chestshoputil:
    description: Main command for ChestShopUtil
    usage: /<command> [args]
    aliases: [csu, chestshoputilities, csutil]
permissions:
  csu.admin:
    default: op
    children:
      csu.bypass.global-maxbuy: true
      csu.bypass.global-maxsell: true
      csu.world.create.*: true
      csu.bypass.maxbuy.*: true
      csu.bypass.maxsell.*: true
      csu.maxshops.*: true
      csu.bypass.item.*: true
      csu.getupdates: true
      csu.bypass.time-period: true
      csu.command.*: true
  csu.command.*:
    default: op
    children:
      csu.command.updatecheck: true
      csu.command.version: true
      csu.command.reload: true
      csu.command.help: true
      csu.command.main: true
  csu.bypass.global-maxbuy:
    default: op
  csu.bypass.global-maxsell:
    default: op
  csu.world.create.*:
    default: op
  csu.bypass.maxbuy.*:
    default: op
  csu.bypass.maxsell.*:
    default: op
  csu.maxshops.*:
    default: op
  csu.maxshops.-1:
    default: op
  csu.bypass.item.*:
    default: op
  csu.getupdate:
    default: op
  csu.bypass.time-period:
    default: op
  csu.command.updatecheck:
    default: op
  csu.command.version:
    default: op
  csu.command.reload:
    default: op
  csu.command.help:
    default: true
  csu.command.main:
    default: true