author: mrmag518
main: com.mrmag518.ChestShopUtil.CSU
version: '1.0'
name: ChestShopUtil
description: "Adds new utilities and features to ChestShop."
softdepend: [ChestShop]
commands:
  chestshoputil:
    description: Main command for ChestShopUtil
    usage: /<command> [args]
    aliases: [csu, chestshoputilities, csutil]
permissions:
  csu.bypass.air-shops:
    default: op
  csu.bypass.global-maxbuy:
    default: op
  csu.bypass.global-maxsell:
    default: op
  csu.world.create.*:
    default: op
  csu.bypass.maxbuy.*:
    default: op
  csu.bypass.maxsell.*:
    default: op
  csu.maxshops.*:
    default: op
  csu.maxshops.-1:
    default: op
  csu.bypass.item.*:
    default: op
  csu.getupdate:
    default: op
  csu.bypass.time-period:
    default: op
  csu.command.updatecheck:
    default: op
  csu.command.version:
    default: op
  csu.command.reload:
    default: op
  csu.command.help:
    default: true
  csu.command.main:
    default: true